# Apply to your concourse-deployment

# Enable prometheus metrics
- type: replace
  path: /instance_groups/name=web/jobs/name=web/properties/prometheus?
  value:
    bind_ip: 172.16.25.214
    bind_port: 80
