---
name: prometheus

instance_groups:
  - name: alertmanager
    azs:
      - ((az2)) 
    instances: 1
    vm_type: ((vm_type))
    persistent_disk: 1_024
    stemcell: default
    networks:
      - name: ((network))
    jobs:
      - name: alertmanager
        release: prometheus
        properties:
          alertmanager:
            route:
              receiver: default
            receivers:
              - name: default
            test_alert:
              daily: true

  - name: prometheus2
    azs:
      - ((az2))
    instances: 1
    vm_type: ((vm_type))
    persistent_disk: 10_240
    stemcell: default
    networks:
      - name: ((network))
    jobs:
      - name: prometheus2
        release: prometheus
        properties:
          prometheus:
            rule_files:
              - /var/vcap/jobs/postgres_alerts/*.alerts.yml
              - /var/vcap/jobs/prometheus_alerts/*.alerts.yml
            scrape_configs:
              - job_name: prometheus
                static_configs:
                - targets:
                  - localhost:9090
      - name: postgres_alerts
        release: prometheus
      - name: prometheus_alerts
        release: prometheus

  - name: database
    azs:
      - ((az2))
    instances: 1
    vm_type: ((vm_type))
    persistent_disk: 10_240
    stemcell: default
    networks:
      - name: ((network)) 
    jobs:
      - name: postgres
        release: postgres
        properties:
          databases:
            port: 5432
            databases:
              - name: grafana
                citext: true
            roles:
              - name: grafana
                password: ((postgres_grafana_password))
      - name: postgres_exporter
        release: prometheus
        properties:
          postgres_exporter:
            datasource_name: postgresql://grafana:((postgres_grafana_password))@127.0.0.1:5432/?sslmode=disable

  - name: grafana
    azs:
      - ((az2))
    instances: 1
    vm_type: ((vm_type))
    persistent_disk: 1_024
    stemcell: default
    networks:
      - name: ((network))
    jobs:
      - name: grafana
        release: prometheus
        properties:
          grafana:
            database:
              type: postgres
              port: 5432
              name: grafana
              user: grafana
              password: ((postgres_grafana_password))
            security:
              admin_user: admin
              admin_password: ((grafana_password))
              secret_key: ((grafana_secret_key))
            dashboards:
            prometheus:
              dashboard_folders:
                - name: Grafana
                  files:
                    - /var/vcap/jobs/grafana_dashboards/*.json
                - name: PostgreSQL
                  files:
                    - /var/vcap/jobs/postgres_dashboards/*.json
                - name: Prometheus
                  files:
                    - /var/vcap/jobs/prometheus_dashboards/*.json
      - name: grafana_dashboards
        release: prometheus
      - name: postgres_dashboards
        release: prometheus
      - name: prometheus_dashboards
        release: prometheus

  - name: nginx
    azs:
      - ((az2))
    instances: 1
    vm_type: ((vm_type))
    stemcell: default
    networks:
      - name: ((network))
        static_ips : [&web-ip ((nginx_ip_address))]
    jobs:
      - name: nginx
        release: prometheus
        properties:
          nginx:
            alertmanager:
              auth_users:
                - name: admin
                  password: ((alertmanager_password))
            prometheus:
              auth_users:
                - name: admin
                  password: ((prometheus_password))

  - name: node-exporter
    azs:
      - ((az2))
    instances: 1
    vm_type: ((vm_type))
    stemcell: default
    networks:
      - name: ((network))
    jobs:
      - name: node_exporter
        release: node-exporter    

variables:
  - name: alertmanager_password
    type: password
  - name: prometheus_password
    type: password
  - name: postgres_grafana_password
    type: password
  - name: grafana_password
    type: password
  - name: grafana_secret_key
    type: password
  - name: uaa_clients_cf_exporter_secret
    type: password
  - name: uaa_clients_firehose_exporter_secret
    type: password

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: postgres
  version: "40"
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=40
  sha1: 343f04f1594c57ecea65638802e94e311cd72688
- name: prometheus
  version: 26.2.0
  url: https://github.com/bosh-prometheus/prometheus-boshrelease/releases/download/v26.2.0/prometheus-26.2.0.tgz
  sha1: 2e47fad474d5f88ad034a45a765c4b3dfb76fbcf
- name: node-exporter
  version: 4.2.0
  url: https://github.com/bosh-prometheus/node-exporter-boshrelease/releases/download/v4.2.0/node-exporter-4.2.0.tgz
  sha1: 7161837435dae4bdc1a9356f7d411be3822666ea
